export const SPAIN_CITIES = [
  'A Coruña',
  'Albacete',
  'Alcalá de Henares',
  'Alcobendas',
  'Alcorcón',
  'Algeciras',
  'Alicante',
  'Almería',
  'Arrecife',
  'Avilés',
  'Badajoz',
  'Badalona',
  'Barcelona',
  'Bilbao',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cartagena',
  'Castellón de la Plana',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Dos Hermanas',
  'Elche',
  'Fuenlabrada',
  'Getafe',
  'Gijón',
  'Girona',
  'Granada',
  'Guadalajara',
  'Huelva',
  'Huesca',
  'Jaén',
  'Jerez de la Frontera',
  'Las Palmas de Gran Canaria',
  'Leganés',
  'León',
  'Lleida',
  'Logroño',
  'Lugo',
  'Madrid',
  'Málaga',
  'Marbella',
  'Mataró',
  'Mérida',
  'Móstoles',
  'Murcia',
  'Ourense',
  'Oviedo',
  'Palencia',
  'Palma',
  'Pamplona',
  'Parla',
  'Pontevedra',
  'Reus',
  'Sabadell',
  'Salamanca',
  'San Cristóbal de La Laguna',
  'San Sebastián',
  'Santa Cruz de Tenerife',
  'Santander',
  'Santiago de Compostela',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Terrassa',
  'Toledo',
  'Torrejón de Ardoz',
  'Valencia',
  'Valladolid',
  'Vitoria-Gasteiz',
  'Zamora',
  'Zaragoza',
]
